from langchain.prompts import PromptTemplate
from langchain.prompts.chat import (
    BaseStringMessagePromptTemplate,
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
)
from langchain.chains.llm import LLMChain
from langchain.callbacks.manager import Callbacks
import subprocess

from omegaconf import DictConfig
from textwrap import dedent
import json
import os
import time
import openai
from typing import Any, Dict, List, Optional

from .utils import *
from .cache import GlobalCache
from .clustered_database import ClusterDatabase


LLM_EXACT_CACHE_TIME_THRESHOLD = 0.5
CACHE_RETRY_THRESHOLD = 70

DB_LIMIT = 209715200  # 200 MB
CACHE_LIMIT = 20971520  # 20 MB


CACHE_GENERATOR_PROMPT_PREFIX = """
You are an expert who can analyze a few example prompts and their corresponding responses and find a common intent from which the responses were generated by the prompts. 
Once you find the common intent, your task is to generate a Python program for it.

The example input prompts provided below will have a prompt template, describing what the LLM was asked to do. This is the static part. 
It will also contain a dictionary of inputs where each key-value pair can be represented as `{{abc:def}}'. To reconstruct the actual prompt that was used to query the LLM, replace each key (`abc') in the template with its corresponding value (`def').
The `def' part in the full prompt is the variable part. Your goal is to analyze how this transformed prompt maps to the given output and find a generalizable pattern that applies across all examples. 
If the responses across all examples are similar (e.g., calling the same API with some parameters), the common pattern must be able to identify how to structure the response based on the static and the variable parts.

Your job is to:
1. Identify a consistent pattern across examples
2. Generate a Python program that extracts key variables using regex and constructs the response accordingly.
3. Ensure the program works for arbitrary prompts that follow the same overall structure.

Here are some guidelines for pattern extraction:
1. The common pattern can be a code to perform a task (extracting a substring from a string) or even a text sentence if all the example responses are sentences with minor changes that do not alter the semantics.
2. For extracting a substring from a string, strip leading/trailing whitespace from the string before matching.
3. Generate regex that captures most prompts and is general enough to apply to new prompts, not just the seen ones (e.g. for keyword extraction, identify where the keyword appears in the sentence and extract them from the similar part of the sentence for any arbitrary user instruction, but following the same prompt template). Please go through all the examples provided before coming up with the regex pattern.
4. Use re.DOTALL if needed (e.g., multi-line string matching).

In the examples below, the input dictionary is written in the form:
```
KEY -> abc
VALUE -> def
```
                                
Example Input Prompts and their Corresponding Responses
==============================================\n"""


CACHE_GENERATOR_PROMPT_SUFFIX = """
Guidelines for the code output format and other generic guidelines:
1. The code must produce an output in the exact format shown in the example responses without `Thought'. For responses in the format of a dictionary, there should be no additional key-value pairs, otherwise, there will be errors in the downstream task that uses this output.
2. Do NOT include `Thought' in the code-generated output, even if it appears in the examples.
3. Put ample `try/except' blocks to catch errors. The code should not crash for any input prompt. If any error occurs, print `None' and the error.
4. Every `if/elif' must be followed by an `else' to handle unmatched conditions. If no conditions are satisfied, the `else' block should print `None' along with the reason.
5. The code should be complete with no EOL or syntax errors.

Guidelines for Code Execution Format:
1. The code generated will be saved as `runnable_code.py'.
2. It will be run as `python3 runnable_code.py <input-dict>'
3. The code must execute without any manual intervention and take the input dictionary in the form {{abc:def}} passed as a string as command-line input <input-dict>.

Final Instructions (strict):
1. Output only the complete Python code.
2. Do not print any explanation, description, or English text apart from the code
3. The output format should exactly match the format of the example responses.

Now Begin!!"""




REGEX_GENERATOR_PROMPT_PREFIX = """
You are an expert who can analyze few example prompts and their outputs when passed to an LLM and find the common pattern among those prompts. 
The common pattern that you have to find is a regex that can cover most of the examples. When the input prompts given as examples below is tested against the regex, it should match.
The regex should be detailed, specific and restrictive such that it should not match any other prompts that do not follow the same pattern as the examples given below. The regex should not be generic.

The regex should match for most of the examples (possibly all). Regex matching means that the input prompt examples follow some common pattern and for any other input prompt following that same common prompt will match with the regex.

You will be given a set of actual prompts that were given as input to LLMs to generate the corresponding outputs. What you should try to do is to find a regex such that all prompts matching the regex will have similar outputs. It is your job to know what a similar output is.
You will also be given the sentence differences between the prompt and the immediate predecessor prompt, i.e. between Prompt i and Prompt (i-1). Sentence differences will indicate how different the prompts. It might be the case that a significant difference between the prompts is in a specific keyword.
If the sentence difference between two prompts is significantly large, then it is often the case that those two prompts are not similar. However, for example, if prompt A is dissimilar to prompt B and prompt B is dissimilar to prompt C, it might be the case that prompt A is similar to prompt C.
It is your job to find the similar prompts.

One way to find similar prompts is to look at their corresponding example outputs. A keyword might be the difference between two prompts, while the same keyword might be present in their corresponding outputs.
If the overall structure of the corresponding outputs in consideration are the same with only the difference in a keyword or sentence construction, their corresponding example prompts are most likely similar. If the two outputs are significantly different, then the example prompts are different as well.
Your task is to find out these similar prompts and generate a regex to match these similar example prompts.
The regex should try to include the entirety of prompt that is same across the similar example prompts and for the portions of the prompts that are different, the regex should try to cover as much as possible and be more specific.

The goal is to find a regex that can match most of the prompts given below. The regex should be able to match any prompt that follows the same pattern as the prompts given below.
Please use Python library `re` to generate the regex. Make sure you put appropriate escape characters wherever necessary. Take extra care and put escape characters in front of double quotes and single quotes.

Example Prompts, their Corresponding Outputs and the Difference Among the Prompts:
=======================================================================\n"""


REGEX_GENERATOR_PROMPT_SUFFIX = """
The regex that will be generated will be saved as `regex.py` and will be run in the format `python3 regex.py <command-line-input>`.
The code should be able to run on its own without any manual intervention and take the string prompt (variable name is `prompt`) as command line input to the code, and return True or False if there is a match with the regex.
You do not need to generate a regex pattern for the outputs, but you must ensure that all the prompts matching the regex should have similar outputs.

NOTE: The regex should be well detailed and cover as much of the text from the examples as possible. It should not be too generic.
It should try to include the entirety of the text present in the example prompts.
The regex pattern should be enclosed within triple quotes.
The code that you will generate should have try-catch blocks wherever necessary to handle exceptions. The code should be such that it does not crash for any input prompt. If an error is catched while execution, the code should print `None`.
If there is any `if` or an `elif` statement in the code, it should also accompany with an `else` statement to handle the case when the `if` condition is not satisfied. If none of the conditions are satisfied, then the code should return `None`.

Strict Insturction: DO NOT output any english text apart from just the code. Take extra care to put escape characters wherever necessary. No need to put escape character before every special character, but should be put wherever necessary such that the pattern string generated is valid. 
                                                                 
Now Begin!!"""


CACHE_VALIDATOR_PROMPT_PREFIX = """
You are an expert evaluator tasked with comparing multiple LLM-generated outputs to their corresponding ground-truth answers. Each answer may be a JSON object, a string, or a code snippet. 
You should validate only the JSON or code portions; ignore any general English descriptions.

Some of the comparisons may be about an API call searching for a product description that users want to buy. 
In those cases, consider a match valid if the key attributes are preserved, even if phrased differently (e.g., "a blue headphone with active noise cancellation" and "blue headphone, active noise cancellation"). 
Often, the LLM-generated answer will be more verbose (former in the example) than the ground-truth answer (latter in the example).

Some important validation rules are: 
1. If the ground truth response is in the JSON format, all keys must be present in the LLM-generated response as well. Extra keys in the JSON mean the result is invalid.
2. If some values within the JSON contain English sentences, check semantic equivalence between the ground truth and the LLM-generated response, not exact wording (e.g. "The product is available in the store" and "The store has the product available" are semantically equivalent).
3. For verbose (in LLM-generated response) vs. concise (in ground-truth response) sentences when comparing for certain keys in the JSON, ensure keywords from the concise form appear in the verbose one.
4. For short phrases or code blocks in the response (e.g., "Buy Item", "Search"), check for exact matches.
5. If the LLM-generated response contains 'null' for some keys in the response, while the ground-truth response contains 'None', treat them as equivalent.
6. Ignore punctuation or numeric formatting (e.g., 10 and 10.00 are equal) when comparing.
7. Ignore quote style (single vs. double quotes) (e.g., "content" and `content' are valid).

Expected Output Format:
```
{{
    "valid": [0 or 1],
    "reason": "The output is correct/incorrect because ..."
}}
```
                                       
"valid" is a list of 0s and 1s (length of the list = number of comparisons done), where 1 at i'th position means a correct match for comparison `i', and 0 means a mismatch.

"reason" should give a single combined explanation for why any outputs were incorrect (e.g., extra keys, wrong structure, mismatched values). 
Do not provide individual explanations per comparison, nor include the comparison number. If an LLM-generated response for any comparison includes an error/exception (e.g., "None: <error>"), include that reason. 
The objective of the reason field is to easily identify mistakes and rectify, hence be concise.

Do not output anything except the specified JSON.
                                       
Strictly follow the format and rules above. Now validate the given examples.
=====================================\n"""



CACHE_REGENERATOR_PROMPT = """
NOTE: The previous generation using LLM was wrong and you are now tasked to regenerate the code.
The reason why the previous generation was wrong is because: {reason}.
Take this into consideration when you are re-generating the template.\n"""



class CacheGenerator:

    def __init__(self, 
                 cfg: DictConfig,
                 global_cache: GlobalCache,
                 database: ClusterDatabase,
                 cache_path: str,
                 results: Dict[str, Any] = {},
                 callbacks: Optional[Callbacks] = None,
                 num_validation_chance: int = 3,
                 num_examples_for_cache: int = 3):
        self.cfg = cfg
        self.global_cache = global_cache
        self.database = database
        self.cache_path = cache_path
        self.callbacks = callbacks
        self.num_validation_chance = num_validation_chance
        self.num_examples_for_cache = num_examples_for_cache
        self.results = results

        self.llm = init_llm(cfg, enable_cache=False)
        self.validator_llm = init_llm(cfg, enable_cache=False)
    

    def generate_plan(self, values, regeneration=False, reason=None):
        key, db_pairs = self.database.get_db(values)
        
        reasoning_inputs = dict()
        example_prompt = ""

        for i, (inp, value) in enumerate(db_pairs.items()):
            example_prompt += f"\n{i+1}:\n"
            example_prompt += f"Prompt Template:\n------------\n{value['prompt_template']}\n\n"
            example_prompt += f"Inputs:\n------\n"
            for elem in inp:
                example_prompt += f"KEY -> {elem[0]}\nVALUE -> {elem[1]}\n\n"
            example_prompt += f"\nOutput:\n------\n{value['output']}\n\n\n"

            if i >= self.num_examples_for_cache:
                break
        
        if regeneration:
            reasoning_inputs["reason"] = reason 
            prompt_template = CACHE_GENERATOR_PROMPT_PREFIX + example_prompt + CACHE_REGENERATOR_PROMPT.format(**reasoning_inputs) + CACHE_GENERATOR_PROMPT_SUFFIX
        else:
            prompt_template = CACHE_GENERATOR_PROMPT_PREFIX + example_prompt + CACHE_GENERATOR_PROMPT_SUFFIX

        prompt = PromptTemplate.from_template(replace_braces(prompt_template))
        print(reasoning_inputs)

        self.llm_chain = LLMChain(llm=self.llm, prompt=prompt, callbacks=self.callbacks)

        plan = self.llm_chain.predict(prompt=self.llm_chain.prompt, **reasoning_inputs)

        self.results["num_abs_calls_for_cache"] += 1
        self.results["caching_retry_per_cluster"][str(key)] = self.results.get("caching_retry_per_cluster", {}).get(str(key), 0) + 1

        if str(key) not in self.results.get("caching_retry_token_length_per_cluster", {}):
            self.results["caching_retry_token_length_per_cluster"][str(key)] = []
        self.results["caching_retry_token_length_per_cluster"][str(key)].append({'input': compute_token_length(prompt_template), 'output': compute_token_length(plan)})

        return key, plan
    

    def generate_regex(self, values):
        key, db_pairs = self.database.get_db(values)
        
        example_prompt = ""
        previous_prompt = None
        for i, (inp, value) in enumerate(db_pairs.items()):
            example_prompt += f"\n{i+1}:\n"
            prompt = value['prompt'].replace('\n', '')
            example_prompt += f"Prompt:\n------------\n{prompt}\n\n"
            example_prompt += f"\nOutput:\n------\n{value['output']}\n\n"

            if previous_prompt is not None:
                diff = sentence_difference(previous_prompt, value['prompt'])
                prompt_diff = f"Difference between Prompt {i} and Prompt {i+1}:\n---------------\n" + "\n".join(diff)
                example_prompt += prompt_diff
                
            previous_prompt = value['prompt']
            if i >= self.num_examples_for_cache:
                break
        
        prompt_template = REGEX_GENERATOR_PROMPT_PREFIX + example_prompt + REGEX_GENERATOR_PROMPT_SUFFIX

        prompt = PromptTemplate.from_template(replace_braces(prompt_template))
        self.llm_chain = LLMChain(llm=self.llm, prompt=prompt, callbacks=self.callbacks)

        plan = self.llm_chain.predict(prompt=self.llm_chain.prompt)
        print("########## Regex ##########")
        print(plan)

        return key, plan


    def validate_cached_output(self, values, plan, examples_to_validate=[]):
        code_to_write = plan.strip('```python\n').rstrip('```')
        with open('runnable_code.py', 'w') as f:
            f.write(code_to_write)

        _, db_pairs = self.database.get_db(values)

        example_prompt = ""
        for i, (inp, value) in enumerate(db_pairs.items()):
            if i == 1:
                continue

            if len(examples_to_validate) > 0 and value['prompt'] not in examples_to_validate:
                continue

            input_dict = tuple_to_dict_key(inp)

            result = subprocess.run(['python3', 'runnable_code.py', json.dumps(input_dict)], stdout=subprocess.PIPE, text=True)
            answer = result.stdout

            example_prompt += f"\n{i+1}:\n"
            example_prompt += f"Answer from LLM:\n------\n{answer}\n\n"
            example_prompt += f"Ground Truth:\n------\n{value['output']}\n\n"
            example_prompt += "++++++++++++\n\n"

            if len(examples_to_validate) == 0 and i >= self.num_examples_for_cache:
                break

        prompt_template = CACHE_VALIDATOR_PROMPT_PREFIX + example_prompt
        prompt = PromptTemplate.from_template(replace_braces(prompt_template))
        self.validator_llm_chain = LLMChain(llm=self.validator_llm, prompt=prompt, callbacks=self.callbacks)

        validation = self.validator_llm_chain.predict(prompt=self.validator_llm_chain.prompt)
        
        return validation
    

    def validate_prompt_with_regex(self, prompt, regex):
        code_to_write = regex.strip('```python\n').rstrip('```')
        with open('runnable_code.py', 'w') as f:
            f.write(code_to_write)

        result = subprocess.run(['python3', 'runnable_code.py', prompt.replace('\n', '')], stdout=subprocess.PIPE, text=True)
        answer = result.stdout
        return bool(answer)
    

    def validate_regex(self, values, regex):
        _, db_pairs = self.database.get_db(values)

        count = 0
        validated_prompts = []
        for inp, value in db_pairs.items():
            answer = self.validate_prompt_with_regex(value['prompt'], regex)
            print(answer)
            if answer:
                count += 1  
                validated_prompts.append(value['prompt'])

        if count >= self.num_examples_for_cache or count == len(db_pairs):
            validation = {"valid": 1,
                          "validated_prompts": validated_prompts,
                          "reason": "Required number of prompts match the regex."}
        else:
            validation = {"valid": 0, 
                          "reason": "Only '{}' out of '{}' prompts match the regex.".format(count, len(db_pairs))}
        
        return validation


    def generate_cache(self, inputs, values):

        _, regex = self.generate_regex(values)
        validation_result = self.validate_regex(values, regex)
        if not validation_result['valid']:
            return self.results
        
        key, plan = self.generate_plan(values, regeneration=False)
        self.results["num_iters_for_cache"] += 1

        i = 0
        while True:
            print("########## Plan ##########")
            print(plan)

            # Validate the output generated by the LLM
            print("########## Validating the output ##########")
            validation = self.validate_cached_output(values, plan, validation_result['validated_prompts'])
            i += 1
            
            print(validation)
            json_validation = json.loads(validation.strip('```json\n').rstrip('```'))
            
            isValid = json_validation['valid']

            
            if isValid:
                # Set the cache for the data
                if os.path.exists(self.cache_path) and os.path.getsize(self.cache_path) >= CACHE_LIMIT:
                    while os.path.getsize(self.cache_path) >= CACHE_LIMIT:
                        cache = self.global_cache.get_entire_cache()
                        cache_keys = cache.keys()
                        cache_count_dict = dict()
                        for key in cache_keys:
                            cache_count_dict[key] = cache[key]['count']

                        cache_count_dict = sorted(cache_count_dict.items(), key=lambda x: x[1])  # Will be of the form [(key, count), (key, count), ...], sorted in an ascending order
                        print(f" ## Cache with key {cache_count_dict[0][0]} is being deleted due to space limit")
                        self.global_cache.delete_cache(cache_count_dict[0][0])

                self.global_cache.set_cache(int(key), {"plan":plan, "regex":regex})
                return self.results
            else:
                if i >= self.num_validation_chance:
                    return self.results
                key, plan = self.generate_plan(values, regeneration=True, reason=json_validation['reason'])

    



class LLMPredict:

    def __init__(self, 
                 global_cache_path: str,
                 database_path: str,
                 cfg: DictConfig,
                 results_path: str = "./results", 
                 num_records_before_caching: int = 4,
                 use_cache: bool = True,
                 max_caching_trials: int = 2,
                 max_caching_pauses: int = 6):
        """ Defining init function for LLMPredict class """
        
        self.num_records_before_caching = num_records_before_caching

        self.num_caching_trials = {}
        self.num_caching_exclusion = {}
        self.CACHING_MAX_TRIALS = max_caching_trials
        self.CACHING_MAX_PAUSES = max_caching_pauses
        self.CACHING_ENABLED = use_cache

        if not os.path.exists(results_path):
            os.makedirs(results_path)

        self.aggregate_results_file = os.path.join(results_path, "results.json")
        self.incident_metric_file = os.path.join(results_path, str(cfg.incident_id), "metric.json")

        if not os.path.exists(self.aggregate_results_file):
            self.results = {"total_calls": 0, 
                            "num_cache_hits": 0, 
                            "num_accurate_cache_hits": 0, 
                            "num_exact_cache_hits": 0,
                            "num_abs_calls_for_cache": 0, 
                            "num_iters_for_cache": 0,
                            "cache_reuse": {},
                            "caching_retry_per_cluster": {},
                            "caching_retry_token_length_per_cluster": {}}
        else:
            self.results = json.load(open(self.aggregate_results_file, "r"))

        if not os.path.exists(self.incident_metric_file):   
            self.incident_metric = {"cache_find_time": [],
                                    "llm_call_time": [],
                                    "cache_call_time": [],
                                    "exact_cache_call_time": [],
                                    "db_entry_time": [],
                                    "sum_diagnosis_time": 0.,
                                    "sum_input_token_length_for_llm": 0,
                                    "sum_output_token_length_for_llm": 0,
                                    "sum_input_token_length_for_semantic_cache": 0,
                                    "sum_output_token_length_for_semantic_cache": 0,
                                    "sum_input_token_length_for_exact_cache": 0,
                                    "sum_output_token_length_for_exact_cache": 0,
                                    "total_calls": 0,
                                    "num_accurate_cache_hits": 0,
                                    "num_exact_cache_hits": 0}
        else:
            self.incident_metric = json.load(open(self.incident_metric_file, "r"))



        self.global_cache = GlobalCache(cache_path=global_cache_path)
        self.database = ClusterDatabase(db_path=database_path)

        self.database_path = database_path
        
        self.cacheGen = CacheGenerator(cfg=cfg, 
                                       global_cache=self.global_cache, 
                                       database=self.database,
                                       cache_path=global_cache_path,
                                       results=self.results,
                                       num_examples_for_cache=num_records_before_caching)


    def is_cache_present(self, keys):
        """ Given a key as input, checks if the key is present in the cache """
        cache = self.global_cache.get_cache(keys)
        return cache


    def find_cache_key(self, value):
        key, _ = self.database.get_db(value)
        return key


    def get_formatted_prompt(self, prompt, inputs):
        formatted_prompt = None

        # Create formatted prompt
        if isinstance(prompt, ChatPromptTemplate):
            prompt_template = ""
            for p in prompt.messages:
                prompt_template += p.prompt.template + "\n"
            formatted_prompt = prompt.format(**inputs)
        else:
            prompt_template = prompt.template
            formatted_prompt = prompt.format(**inputs)

        return prompt_template, formatted_prompt
    

    def find_and_validate_cache(self, prompt):
        # Check if the cache is present
        CACHE_FIND_START_TIME = time.time()
        cache = None
        key = self.find_cache_key(prompt)

        # Bookkeeping to refrain from excessive caching
        if key not in self.num_caching_trials:
            self.num_caching_trials[key] = 0
            self.num_caching_exclusion[key] = 0

        if key is not None:
            cache = self.is_cache_present(int(key))
            print(cache)
        
        validation_result = False
        if cache:
            # Validate incoming prompt agsint the regex stored in the cache
            validation_result = self.cacheGen.validate_prompt_with_regex(prompt, cache['regex'])
            print(f'Prompt Validation Result with Key {key}: {validation_result}')
            if 'plan' not in cache:
                validation_result = False
        
        CACHE_FIND_END_TIME = time.time()

        return cache, key, validation_result, (CACHE_FIND_END_TIME - CACHE_FIND_START_TIME)
    

    def llm_predict_with_key(self,
                            llm_chain: LLMChain,
                            keys: str,
                            inputs: dict,
                            callbacks: Optional[Callbacks] = None):
        
        cache = self.is_cache_present(keys)

        if cache:
            plan = cache["plan"]
            code_to_write = plan.strip('```python\n').rstrip('```')
            with open('runnable_code.py', 'w') as f:
                f.write(code_to_write)

            result = subprocess.run(['python3', 'runnable_code.py', json.dumps(inputs)], stdout=subprocess.PIPE, text=True)
            answer = result.stdout
            print('Answer:', answer)

            # TODO: Validate the answer
            
            return answer
        else:
            # if keys not in self.keys_to_exclude:
            #     # # If the number of records in the database is greater than the threshold, cache the records
            #     if self.database.len(keys) >= self.num_records_before_caching:
            #         self.cacheGen.generate_cache(keys)

            prompt = llm_chain.prompt

            if isinstance(prompt, ChatPromptTemplate):
                prompt_template = ""
                for p in prompt.messages:
                    prompt_template += p.prompt.template + "\n"
                formatted_prompt = prompt.format(**inputs)
            else:
                prompt_template = llm_chain.prompt.template
                formatted_prompt = prompt.format(**inputs)

            # # Find the variables in the prompt template and find the corresponding values of those variables from the inputs dictionary
            # # Those values will be replaced in the prompt template using format string
            # input_keys = [word.strip('{}') for word in prompt_template.split() if word.startswith('{') and word.endswith('}')]
            # input_vals = {key: inputs[key] for key in input_keys}
            # print('Input Vals:', input_vals)

            # Use LLM to predict the response to the prompt
            answer = llm_chain.predict(prompt=llm_chain.prompt, **inputs, callbacks=callbacks)
            print('Answer:', answer)
            

            # Save the answer to database for cache generation
            database_key = keys
            db_inputs = dict_to_tuple_key(inputs)
            database_val = {db_inputs: {"prompt_template": prompt_template, 
                                        "prompt": formatted_prompt, 
                                        "output": answer}}
            
            self.database.set_db(database_key, database_val)

            # If the number of records in the database is greater than the threshold, cache the records
            if self.database.len(database_key) >= self.num_records_before_caching:
                self.cacheGen.generate_cache(keys)

            return answer
        
    
    def llm_predict_no_key(self,
                           llm_chain: LLMChain,
                           inputs: dict,
                           callbacks: Optional[Callbacks] = None):
        
        USE_LLM = True
        cached_answer = None

        prompt = llm_chain.prompt
        prompt_template, formatted_prompt = self.get_formatted_prompt(prompt, inputs)
        input_token_length = compute_token_length(formatted_prompt)
        
        if self.CACHING_ENABLED:
            # find, validate and generate cached answer only if caching is enabled
            cache, key, validation_result, cache_find_time = self.find_and_validate_cache(formatted_prompt)
            self.incident_metric["cache_find_time"].append(cache_find_time)

            if validation_result:
                print("#### Cache Retrieved ####")
                self.results["num_cache_hits"] += 1
                plan = cache["plan"]
                code_to_write = plan.strip('```python\n').rstrip('```')
                with open('runnable_code.py', 'w') as f:
                    f.write(code_to_write)

                CACHE_USE_START_TIME = time.time()
                try:
                    result = subprocess.run(['python3', 'runnable_code.py', json.dumps(inputs)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
                except subprocess.CalledProcessError as e:
                    print("Cached Code stopped running with error ", e.stderr)  
                else:
                    cached_answer = result.stdout
                    print('Answer:', cached_answer)
                    if "None" not in cached_answer and "null" not in cached_answer:
                        if cached_answer and not cached_answer.isspace():
                            USE_LLM = False
                            CACHE_USE_END_TIME = time.time()
                            self.incident_metric["cache_call_time"].append(CACHE_USE_END_TIME - CACHE_USE_START_TIME)
                            self.incident_metric["sum_diagnosis_time"] += CACHE_USE_END_TIME - CACHE_USE_START_TIME

        
        if not USE_LLM:
            # Logging results
            self.results["num_accurate_cache_hits"] += 1
            self.results["cache_reuse"][str(key)] = self.results.get("cache_reuse", {}).get(str(key), 0) + 1
            self.incident_metric["num_accurate_cache_hits"] += 1
            self.incident_metric["sum_input_token_length_for_semantic_cache"] += input_token_length
            self.incident_metric["sum_output_token_length_for_semantic_cache"] += compute_token_length(cached_answer)

            return cached_answer
        else:
            print("*********** USING LLM ***********")
            LLM_USE_START_TIME = time.time()
            # Use LLM to predict the response to the prompt
            answer = llm_chain.predict(prompt=llm_chain.prompt, **inputs, callbacks=callbacks)
            print('Answer:', answer)

            LLM_USE_END_TIME = time.time()

            llm_call_time = LLM_USE_END_TIME - LLM_USE_START_TIME
            self.incident_metric["sum_diagnosis_time"] += llm_call_time


            # Check whether llm call time is over a threshold or not. 
            # If no, then exact caching was done and update the metrics accordingly
            if llm_call_time > LLM_EXACT_CACHE_TIME_THRESHOLD:
                print("#### NOT Exact Cache ####")
                self.incident_metric["sum_input_token_length_for_llm"] += input_token_length
                self.incident_metric["sum_output_token_length_for_llm"] += compute_token_length(answer)
                self.incident_metric["llm_call_time"].append(llm_call_time)
            else:
                print("#### Exact Cache ####")
                self.results["num_exact_cache_hits"] += 1
                self.incident_metric["num_exact_cache_hits"] += 1
                self.incident_metric["sum_input_token_length_for_exact_cache"] += input_token_length
                self.incident_metric["sum_output_token_length_for_exact_cache"] += compute_token_length(answer)
                self.incident_metric["exact_cache_call_time"].append(llm_call_time)


            if self.CACHING_ENABLED:
                # Create inputs and outputs to insert it into the clustered databased
                db_inputs = dict_to_tuple_key(inputs)
                database_val = {"prompt_template": prompt_template, 
                                "prompt": formatted_prompt, 
                                "output": answer}
                
                if os.path.exists(self.database_path) and os.path.getsize(self.database_path) >= DB_LIMIT:
                    # if database size is more than limit, then don't add entry to the database
                    print("Database size is more than limit, skipping database entry")
                    pass
                else:
                    DB_ENTRY_START_TIME = time.time()
                    ret_val, key = self.database.set_db(db_inputs, database_val)
                    DB_ENTRY_END_TIME = time.time()
                    
                    self.incident_metric["db_entry_time"].append(DB_ENTRY_END_TIME - DB_ENTRY_START_TIME)


                    # Check if caching retries have exceeded some threshold
                    if str(key) not in self.results["caching_retry_per_cluster"] or \
                        (str(key) in self.results["caching_retry_per_cluster"] and self.results["caching_retry_per_cluster"][str(key)] <= CACHE_RETRY_THRESHOLD):
                        
                        if key not in self.num_caching_trials:
                            self.num_caching_trials[key] = 0
                            self.num_caching_exclusion[key] = 0
                        
                        # Check if consecutive caching trials have exceeded a threhsold or not
                        print(f"NUM CACHING TRIALS: {self.num_caching_trials[key]}  |  NUM CACHING EXCLUSION: {self.num_caching_exclusion[key]}")
                        # Switching when to again try caching
                        if self.num_caching_trials[key] >= self.CACHING_MAX_TRIALS:
                            self.num_caching_exclusion[key] += 1

                        if self.num_caching_exclusion[key] >= self.CACHING_MAX_PAUSES:
                            self.num_caching_exclusion[key] = 0
                            self.num_caching_trials[key] = 0

                        print("Inside...")
                        print(self.num_caching_trials[key])

                        # If the number of records in the database is greater than the threshold, cache the records
                        if self.database.len(database_val) >= self.num_records_before_caching:
                            if self.num_caching_trials[key] <= self.CACHING_MAX_TRIALS:
                                self.results = self.cacheGen.generate_cache(db_inputs, database_val)
                                self.num_caching_trials[key] += 1

            return answer


    def llm_predict(self, 
                    llm_chain: LLMChain,  
                    inputs: dict, 
                    keys: Optional[str] = None,
                    callbacks: Optional[Callbacks] = None):
        
        if keys:
            answer = self.llm_predict_with_key(llm_chain, keys, inputs, callbacks)
        else:
            self.results["total_calls"] += 1
            self.incident_metric["total_calls"] += 1
            answer = self.llm_predict_no_key(llm_chain=llm_chain, inputs=inputs, callbacks=callbacks)

        json.dump(self.results, open(self.aggregate_results_file, "w"))
        json.dump(self.incident_metric, open(self.incident_metric_file, "w"))
        
        return answer